# BIP Mental Health Technical Challenge 2023 - GROUP 2

### Importing all the necessary libraries

In [1]:
#import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import svm
import matplotlib.pyplot as plt


In [2]:
#loading in the dataset as a dataframe
train_data = pd.read_csv("training_set.csv")

In [3]:
#inspecting the dataframe
train_data

X_STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0           29      11  11092021      11     9   2021      1100  2021010133   
1           28       1   3302021       3    30   2021      1100  2021001524   
2           19       8   8252021       8    25   2021      1100  2021006677   
3           27       9   9302021       9    30   2021      1100  2021012199   
4           51       9  10282021      10    28   2021      1200  2021008821   
...        ...     ...       ...     ...   ...    ...       ...         ...   
79995        8      10  10292021      10    29   2021      1100  2021004748   
79996       50       6   7092021       7     9   2021      1100  2021004094   
79997       18       6   6062021       6     6   2021      1100  2021005595   
79998       25      11  11022021      11     2   2021      1200  2021007056   
79999       31       6   7122021       7    12   2021      1100  2021007149   

            X_PSU  CTELENM1  ...  X_FRUTSU1  X_VEGESU1  X_FRTLT1A  X_VEGLT1A  \
0      2021010133       NaN  ...        NaN      200.0          9          1   
1      2021001524       NaN  ...      200.0      160.0          1          1   
2      2021006677       NaN  ...       43.0       26.0          2          2   
3      2021012199       NaN  ...       10.0      279.0          2          1   
4      2021008821       NaN  ...        NaN        NaN          9          9   
...           ...       ...  ...        ...        ...        ...        ...   
79995  2021004748       NaN  ...       13.0      106.0          2          1   
79996  2021004094       NaN  ...      213.0      243.0          1          1   
79997  2021005595       NaN  ...      143.0      185.0          1          1   
79998  2021007056       NaN  ...        NaN        NaN          9          9   
79999  2021007149       NaN  ...       86.0      185.0          2          1   

       X_FRT16A  X_VEG23A  X_FRUITE1  X_VEGETE1  Outcome  Record_ID  
0             1         1          1          0      Neg     206053  
1             1         1          0          0      Pos     193085  
2             1         1          0          0      Neg     100511  
3             1         1          0          0      Pos     187824  
4             1         1          1          1      Neg     397876  
...         ...       ...        ...        ...      ...        ...  
79995         1         1          0          0      Neg      37937  
79996         1         1          0          0      Neg     386586  
79997         1         1          0          0      Neg      89557  
79998         1         1          1          1      Neg     166054  
79999         1         1          0          0      Neg     221570  

[80000 rows x 288 columns]

In [41]:
pd.set_option('display.max_columns', None)
train_data.head()

X_STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0       29      11  11092021      11     9   2021      1100  2021010133   
1       28       1   3302021       3    30   2021      1100  2021001524   
2       19       8   8252021       8    25   2021      1100  2021006677   
3       27       9   9302021       9    30   2021      1100  2021012199   
4       51       9  10282021      10    28   2021      1200  2021008821   

        X_PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  CELPHON1  LADULT1  \
0  2021010133       NaN       NaN       NaN       NaN       NaN      NaN   
1  2021001524       NaN       NaN       NaN       NaN       NaN      NaN   
2  2021006677       NaN       NaN       NaN       NaN       NaN      NaN   
3  2021012199       NaN       NaN       NaN       NaN       NaN      NaN   
4  2021008821       NaN       NaN       NaN       NaN       NaN      NaN   

   COLGSEX  NUMADULT  LANDSEX  NUMMEN  NUMWOMEN  RESPSLCT  SAFETIME  CTELNUM1  \
0      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
1      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
2      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
3      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
4      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   

   CELLFON5  CADULT1  CELLSEX  PVTRESD3  CCLGHOUS  CSTATE1  LANDLINE  HHADULT  \
0       1.0      1.0      2.0       1.0       NaN      1.0       1.0      3.0   
1       1.0      1.0      1.0       1.0       NaN      1.0       2.0      2.0   
2       1.0      1.0      1.0       1.0       NaN      1.0       2.0      4.0   
3       1.0      1.0      1.0       1.0       NaN      1.0       2.0      2.0   
4       1.0      1.0      1.0       1.0       NaN      1.0       2.0      2.0   

   SEXVAR  GENHLTH  PHYSHLTH  PRIMINSR  PERSDOC3  MEDCOST1  CHECKUP1  \
0       2      3.0      30.0       5.0         1       1.0         1   
1       1      4.0      15.0       3.0         1       2.0         1   
2       1      2.0      88.0       1.0         1       2.0         1   
3       1      4.0      88.0       3.0         2       2.0         1   
4       1      3.0      88.0       1.0         1       2.0         1   

   EXERANY2  BPHIGH6  BPMEDS  CHOLCHK3  TOLDHI3  CHOLMED3  CVDINFR4  CVDCRHD4  \
0         1        1     1.0         2      1.0       2.0         2         2   
1         1        1     1.0         2      2.0       2.0         2         2   
2         1        3     NaN         1      NaN       NaN         2         2   
3         1        4     NaN         2      1.0       2.0         2         2   
4         1        3     NaN         2      2.0       2.0         2         2   

   CVDSTRK3  ASTHMA3  ASTHNOW  CHCSCNCR  CHCOCNCR  CHCCOPD3  CHCKDNY2  \
0         2        2      NaN         2         2         1         2   
1         2        1      1.0         1         2         1         2   
2         2        1      1.0         2         2         2         2   
3         2        2      NaN         2         2         2         2   
4         2        2      NaN         2         2         2         2   

   HAVARTH5  ARTHEXER  ARTHEDU  LMTJOIN3  ARTHDIS2  JOINPAI2  MARITAL  EDUCA  \
0         1       1.0      2.0       1.0       1.0       7.0        4    3.0   
1         1       2.0      2.0       1.0       2.0       6.0        1    6.0   
2         2       NaN      NaN       NaN       NaN       NaN        5    6.0   
3         2       NaN      NaN       NaN       NaN       NaN        4    5.0   
4         2       NaN      NaN       NaN       NaN       NaN        1    6.0   

   RENTHOM1  NUMHHOL3  NUMPHON3  CPDEMO1B  VETERAN3  EMPLOY1  CHILDREN  \
0         2       NaN       NaN       1.0       2.0      8.0       3.0   
1         1       NaN       NaN       1.0       1.0      1.0      88.0   
2         2       NaN       NaN       1.0       2.0      3.

### Explorative Data Analysis EDA

In [4]:
train_data.shape

(80000, 288)

In [5]:
train_data.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Columns: 288 entries, X_STATE to Record_ID
dtypes: float64(211), int64(76), object(1)
memory usage: 175.8+ MB


In [6]:
train_data.describe()

X_STATE        FMONTH         IDATE        IMONTH          IDAY  \
count  80000.000000  80000.000000  8.000000e+04  80000.000000  80000.000000   
mean      30.833350      6.438525  6.716038e+06      6.563363     15.065437   
std       15.225949      3.431110  3.458150e+06      3.457623      8.625890   
min        1.000000      1.000000  1.012022e+06      1.000000      1.000000   
25%       20.000000      4.000000  3.302021e+06      3.000000      8.000000   
50%       31.000000      6.000000  7.062021e+06      7.000000     15.000000   
75%       42.000000      9.000000  1.005202e+07     10.000000     22.000000   
max       78.000000     12.000000  1.231202e+07     12.000000     31.000000   

              IYEAR      DISPCODE         SEQNO         X_PSU  CTELENM1  ...  \
count  80000.000000  80000.000000  8.000000e+04  8.000000e+04   19972.0  ...   
mean    2021.054112   1117.747500  2.021006e+09  2.021006e+09       1.0  ...   
std        0.226241     38.207257  6.449445e+03  6.449445e+03       0.0  ...   
min     2021.000000   1100.000000  2.021000e+09  2.021000e+09       1.0  ...   
25%     2021.000000   1100.000000  2.021002e+09  2.021002e+09       1.0  ...   
50%     2021.000000   1100.000000  2.021004e+09  2.021004e+09       1.0  ...   
75%     2021.000000   1100.000000  2.021008e+09  2.021008e+09       1.0  ...   
max     2022.000000   1200.000000  2.021039e+09  2.021039e+09       1.0  ...   

          X_VEGRES1     X_FRUTSU1     X_VEGESU1     X_FRTLT1A     X_VEGLT1A  \
count  80000.000000  71204.000000  69528.000000  80000.000000  80000.000000   
mean       0.869100    172.884417    268.913747      2.237963      2.218375   
std        0.337293    667.583491   1033.643046      2.421298      2.657899   
min        0.000000      0.000000      0.000000      1.000000      1.000000   
25%        1.000000     50.000000    113.000000      1.000000      1.000000   
50%        1.000000    100.000000    163.000000      1.000000      1.000000   
75%        1.000000    200.000000    229.000000      2.000000      2.000000   
max        1.000000  19800.000000  31114.000000      9.000000      9.000000   

           X_FRT16A      X_VEG23A     X_FRUITE1     X_VEGETE1      Record_ID  
count  80000.000000  80000.000000  80000.000000  80000.000000   80000.000000  
mean       0.995250      0.992650      0.119450      0.145600  219332.834525  
std        0.068757      0.085417      0.338649      0.372964  125754.189557  
min        0.000000      0.000000      0.000000      0.000000       9.000000  
25%        1.000000      1.000000      0.000000      0.000000  111215.750000  
50%        1.000000      1.000000      0.000000      0.000000  219030.500000  
75%        1.000000      1.000000      0.000000      0.000000  328283.000000  
max        1.000000      1.000000      2.000000      2.000000  436173.000000  

[8 rows x 287 columns]

In [7]:
train_data.isnull().sum()

X_STATE      0
FMONTH       0
IDATE        0
IMONTH       0
IDAY         0
            ..
X_VEG23A     0
X_FRUITE1    0
X_VEGETE1    0
Outcome      0
Record_ID    0
Length: 288, dtype: int64

In [8]:
train_data.columns

Index(['X_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE',
       'SEQNO', 'X_PSU', 'CTELENM1',
       ...
       'X_FRUTSU1', 'X_VEGESU1', 'X_FRTLT1A', 'X_VEGLT1A', 'X_FRT16A',
       'X_VEG23A', 'X_FRUITE1', 'X_VEGETE1', 'Outcome', 'Record_ID'],
      dtype='object', length=288)

In [9]:
#!pip install pandas_profiling

In [10]:
from pandas_profiling import ProfileReport

C:\Users\OSHODI IFEDAYO\anaconda3\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
#ProfileReport(train_data)

In [12]:
train_data.X_STATE.unique()

array([29, 28, 19, 27, 51, 50, 38, 16, 23, 31,  9, 17, 13, 54, 30, 36,  6,
        8, 47, 37, 55, 39, 34, 24,  5, 48, 20, 41, 56, 53, 25, 21, 26, 33,
       49, 45, 11, 18,  4, 22, 35, 44, 40, 46,  2, 72, 42, 10,  1, 32, 78,
       15, 66], dtype=int64)

In [13]:
train_data.FMONTH.unique()

array([11,  1,  8,  9,  2, 12,  3,  5,  6,  7,  4, 10], dtype=int64)

In [14]:
train_data.IDATE.unique()

array([11092021,  3302021,  8252021,  9302021, 10282021,  4052021,
        1222022, 12112021,  3012021,  5112021,  4062021,  2252021,
        9252021,  2142021,  7062021,  7222021, 12022021,  7202021,
       12142021,  5012021,  3042021, 12312021,  1062022,  4082021,
        9162021,  4282021,  3122021,  8232021,  9062021,  4272021,
        2282021,  5282021,  1032021, 11172021,  7172021, 11162021,
       11022021,  3112021,  6012021,  6142021,  6162021,  1082022,
        8112021,  3252021,  6052021,  3222021,  4132021,  7102021,
        9192021,  8222021, 12172021,  8182021,  3242021,  5072021,
       12152021, 10172021,  6292021,  7072021,  3182021,  3072021,
        1112022,  6092021,  3162021,  2062021,  4172021,  9262021,
        7282021, 12062021,  3282021, 10052021, 10012021, 11292021,
        9132021, 11012021,  1042022,  6032021,  3232021, 11232021,
        4152021,  2112021,  7272021,  8042021,  7012021,  1312021,
        1262021, 11152021, 10092021,  9082021,  5202021, 10132

In [15]:
train_data.IDAY.unique()

array([ 9, 30, 25, 28,  5, 22, 11,  1,  6, 14,  2, 20,  4, 31,  8, 16, 12,
       23, 27,  3, 17, 13, 10, 19, 18, 24,  7, 15, 29, 26, 21],
      dtype=int64)

In [16]:
train_data.IYEAR.unique()

array([2021, 2022], dtype=int64)

In [17]:
train_data.DISPCODE.unique()

array([1100, 1200], dtype=int64)

In [18]:
train_data.SEQNO.unique()

array([2021010133, 2021001524, 2021006677, ..., 2021024781, 2021015726,
       2021015706], dtype=int64)

In [19]:
sum(pd.isnull(train_data['SEQNO']))

0

In [20]:
train_data.X_PSU.unique()

array([2021010133, 2021001524, 2021006677, ..., 2021024781, 2021015726,
       2021015706], dtype=int64)

In [21]:
sum(pd.isnull(train_data['X_PSU']))

0

In [22]:
train_data.CTELENM1.unique()

array([nan,  1.])

In [23]:
sum(pd.isnull(train_data['CTELENM1']))

60028

In [24]:
train_data.PVTRESD1.unique()

array([nan,  1.,  2.])

In [25]:
sum(pd.isnull(train_data['PVTRESD1']))

60028

In [26]:
train_data.COLGHOUS.unique()

array([nan,  1.])

In [27]:
sum(pd.isnull(train_data['COLGHOUS']))

79995

In [28]:
train_data.STATERE1.unique()

array([nan,  1.])

In [29]:
sum(pd.isnull(train_data['STATERE1']))

60028

In [30]:
train_data.CELPHON1.unique()

array([nan,  2.])

In [31]:
sum(pd.isnull(train_data['CELPHON1']))

60028

In [32]:
train_data.LADULT1.unique()

array([nan,  1.,  2.])

In [33]:
sum(pd.isnull(train_data['LADULT1']))

60028

In [34]:
train_data.COLGSEX.unique()

array([nan,  1.,  2.])

In [35]:
sum(pd.isnull(train_data['COLGSEX']))

79995

In [37]:
train_data.NUMADULT.unique()

array([nan,  1.,  2.,  3.,  4.,  5.,  6., 10.,  7., 12.,  8.])

In [38]:
sum(pd.isnull(train_data['NUMADULT']))

60031

In [39]:
#Label: Are you male or female? Section Name: Land Line Introduction
train_data.LANDSEX.unique()

array([nan,  1.,  2.,  9.])

In [40]:
sum(pd.isnull(train_data['LANDSEX']))

71347

In [42]:
#Number of Adult men in Household
train_data.NUMMEN.unique()

array([nan,  1.,  2.,  0.,  3.,  4.,  5.,  8.])

In [43]:
sum(pd.isnull(train_data['NUMMEN']))

69098

In [47]:
#Number of Adult women in Household
train_data.NUMWOMEN.unique()

array([nan,  1.,  2.,  0.,  3.,  4.,  7.,  5., 11.])

In [50]:
sum(pd.isnull(train_data['NUMWOMEN']))

69098

In [51]:
#Respondent selection
train_data.RESPSLCT.unique()

array([nan,  2.,  1.,  9.])

In [52]:
sum(pd.isnull(train_data['RESPSLCT']))

69212

In [53]:
#Safe time to talk
train_data.SAFETIME.unique()

array([ 1., nan])

In [54]:
sum(pd.isnull(train_data['SAFETIME']))

19972

In [55]:
#Correct Phone Number?
train_data.CTELNUM1.unique()

array([ 1., nan])

In [56]:
sum(pd.isnull(train_data['CTELNUM1']))

19972

In [57]:
#Is this a cell phone?
train_data.CELLFON5.unique()

array([ 1., nan])

In [59]:
sum(pd.isnull(train_data['CELLFON5']))

19972

In [36]:
pd.set_option('display.max_columns', None)
train_data.head()

X_STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0       29      11  11092021      11     9   2021      1100  2021010133   
1       28       1   3302021       3    30   2021      1100  2021001524   
2       19       8   8252021       8    25   2021      1100  2021006677   
3       27       9   9302021       9    30   2021      1100  2021012199   
4       51       9  10282021      10    28   2021      1200  2021008821   

        X_PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  CELPHON1  LADULT1  \
0  2021010133       NaN       NaN       NaN       NaN       NaN      NaN   
1  2021001524       NaN       NaN       NaN       NaN       NaN      NaN   
2  2021006677       NaN       NaN       NaN       NaN       NaN      NaN   
3  2021012199       NaN       NaN       NaN       NaN       NaN      NaN   
4  2021008821       NaN       NaN       NaN       NaN       NaN      NaN   

   COLGSEX  NUMADULT  LANDSEX  NUMMEN  NUMWOMEN  RESPSLCT  SAFETIME  CTELNUM1  \
0      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
1      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
2      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
3      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   
4      NaN       NaN      NaN     NaN       NaN       NaN       1.0       1.0   

   CELLFON5  CADULT1  CELLSEX  PVTRESD3  CCLGHOUS  CSTATE1  LANDLINE  HHADULT  \
0       1.0      1.0      2.0       1.0       NaN      1.0       1.0      3.0   
1       1.0      1.0      1.0       1.0       NaN      1.0       2.0      2.0   
2       1.0      1.0      1.0       1.0       NaN      1.0       2.0      4.0   
3       1.0      1.0      1.0       1.0       NaN      1.0       2.0      2.0   
4       1.0      1.0      1.0       1.0       NaN      1.0       2.0      2.0   

   SEXVAR  GENHLTH  PHYSHLTH  PRIMINSR  PERSDOC3  MEDCOST1  CHECKUP1  \
0       2      3.0      30.0       5.0         1       1.0         1   
1       1      4.0      15.0       3.0         1       2.0         1   
2       1      2.0      88.0       1.0         1       2.0         1   
3       1      4.0      88.0       3.0         2       2.0         1   
4       1      3.0      88.0       1.0         1       2.0         1   

   EXERANY2  BPHIGH6  BPMEDS  CHOLCHK3  TOLDHI3  CHOLMED3  CVDINFR4  CVDCRHD4  \
0         1        1     1.0         2      1.0       2.0         2         2   
1         1        1     1.0         2      2.0       2.0         2         2   
2         1        3     NaN         1      NaN       NaN         2         2   
3         1        4     NaN         2      1.0       2.0         2         2   
4         1        3     NaN         2      2.0       2.0         2         2   

   CVDSTRK3  ASTHMA3  ASTHNOW  CHCSCNCR  CHCOCNCR  CHCCOPD3  CHCKDNY2  \
0         2        2      NaN         2         2         1         2   
1         2        1      1.0         1         2         1         2   
2         2        1      1.0         2         2         2         2   
3         2        2      NaN         2         2         2         2   
4         2        2      NaN         2         2         2         2   

   HAVARTH5  ARTHEXER  ARTHEDU  LMTJOIN3  ARTHDIS2  JOINPAI2  MARITAL  EDUCA  \
0         1       1.0      2.0       1.0       1.0       7.0        4    3.0   
1         1       2.0      2.0       1.0       2.0       6.0        1    6.0   
2         2       NaN      NaN       NaN       NaN       NaN        5    6.0   
3         2       NaN      NaN       NaN       NaN       NaN        4    5.0   
4         2       NaN      NaN       NaN       NaN       NaN        1    6.0   

   RENTHOM1  NUMHHOL3  NUMPHON3  CPDEMO1B  VETERAN3  EMPLOY1  CHILDREN  \
0         2       NaN       NaN       1.0       2.0      8.0       3.0   
1         1       NaN       NaN       1.0       1.0      1.0      88.0   
2         2       NaN       NaN       1.0       2.0      3.

In [61]:
#Are you 18 years of age or older?
train_data.CADULT1.unique()

array([ 1., nan])

In [62]:
sum(pd.isnull(train_data['CADULT1']))

19972